// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:tmap_map_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';



mixin com_tencent_map_sdk_comps_offlinemap_OfflineItemController on java_lang_Object {
  

  

  @override
  final String tag__ = 'tmap_map_fluttify';

  

  

  @mustCallSuper
  Future<bool> checkInvalidate() {}
  
  @mustCallSuper
  Future<bool> open() {}
  
  @mustCallSuper
  Future<bool> close() {}
  
  @mustCallSuper
  Future<void> startDownload() {}
  
  @mustCallSuper
  Future<void> stopDownload() {}
  
  @mustCallSuper
  Future<bool> removeCache() {}
  
}

