//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

#import "TmapMapFluttifyPlugin.h"

NS_ASSUME_NONNULL_BEGIN

@interface TmapMapFluttifyPlugin (SubHandler1)
- (NSDictionary<NSString*, Handler>*) getSubHandler1;
@end

NS_ASSUME_NONNULL_END
