name: tmap_map_fluttify_example
description: Demonstrates how to use the tmap_map_fluttify plugin.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tmap_map_fluttify:
    path: ../
  permission_handler: ^5.0.0+hotfix.6
  oktoast: ^2.3.1+1
  demo_widgets: ^0.2.1
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/