name: tmap_map_fluttify
description: An `Tencent Map` Map Component, Powered By `Fluttify` Compiler, A Dart Bindings Generator For Native SDK.
version: 0.3.0
author: yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  uni_map_platform_interface: ^0.0.6
  foundation_fluttify: ^0.9.9
  core_location_fluttify: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.tmap_map_fluttify
        pluginClass: TmapMapFluttifyPlugin
      ios:
        pluginClass: TmapMapFluttifyPlugin