// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:tmap_map_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';



mixin com_tencent_tencentmap_mapsdk_maps_model_GroundOverlay on java_lang_Object {
  

  

  @override
  final String tag__ = 'tmap_map_fluttify';

  

  

  @mustCallSuper
  Future<void> setBitmap(com_tencent_tencentmap_mapsdk_maps_model_BitmapDescriptor var1) {}
  
  @mustCallSuper
  Future<void> setLatLongBounds(com_tencent_tencentmap_mapsdk_maps_model_LatLngBounds var1) {}
  
  @mustCallSuper
  Future<void> setPosition(com_tencent_tencentmap_mapsdk_maps_model_LatLng var1) {}
  
  @mustCallSuper
  Future<void> setZoom(double var1) {}
  
  @mustCallSuper
  Future<void> setAnchor(double var1, double var2) {}
  
  @mustCallSuper
  Future<void> setAlpha(double var1) {}
  
  @mustCallSuper
  Future<void> setVisibility(bool var1) {}
  
  @mustCallSuper
  Future<void> setZindex(int var1) {}
  
  @mustCallSuper
  Future<void> setLevel(int var1) {}
  
  @mustCallSuper
  Future<void> remove() {}
  
}

