// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:tmap_map_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';



mixin com_tencent_tencentmap_mapsdk_maps_model_MarkerGroup on java_lang_Object {
  

  

  @override
  final String tag__ = 'tmap_map_fluttify';

  

  

  @mustCallSuper
  Future<String> getId() {}
  
  @mustCallSuper
  Future<void> addMarkerById(String var1) {}
  
  @mustCallSuper
  Future<void> addMarker(com_tencent_tencentmap_mapsdk_maps_model_Marker var1) {}
  
  @mustCallSuper
  Future<void> addMarkerList(List<com_tencent_tencentmap_mapsdk_maps_model_Marker> var1) {}
  
  @mustCallSuper
  Future<bool> removeMarker(com_tencent_tencentmap_mapsdk_maps_model_Marker var1) {}
  
  @mustCallSuper
  Future<bool> removeMarkerById(String var1) {}
  
  @mustCallSuper
  Future<void> clear() {}
  
  @mustCallSuper
  Future<com_tencent_tencentmap_mapsdk_maps_model_Marker> findMarkerById(String var1) {}
  
  @mustCallSuper
  Future<List<com_tencent_tencentmap_mapsdk_maps_model_Marker>> getMarkerList() {}
  
  @mustCallSuper
  Future<List<String>> getMarkerIdList() {}
  
  @mustCallSuper
  Future<bool> containMarker(com_tencent_tencentmap_mapsdk_maps_model_Marker var1) {}
  
  @mustCallSuper
  Future<bool> containMarkerById(String var1) {}
  
  @mustCallSuper
  Future<bool> updateMarkerOptionById(String var1, com_tencent_tencentmap_mapsdk_maps_model_MarkerOptions var2) {}
  
  @mustCallSuper
  Future<void> setMarkerGroupOnTapMapInfoWindowHidden(bool var1) {}
  
  @mustCallSuper
  Future<void> setMarkerGroupOnTapMapBubblesHidden(bool var1) {}
  
  @mustCallSuper
  Future<bool> setMarkerOnTapMapBubblesHidden(com_tencent_tencentmap_mapsdk_maps_model_Marker var1, bool var2) {}
  
  @mustCallSuper
  Future<bool> setOnTapMapBubblesHiddenById(String var1, bool var2) {}
  
}

