// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum com_tencent_tencentmap_mapsdk_maps_model_OverSeaSource {
  DEFAULT /* null */,
  SPARE /* null */
}

extension com_tencent_tencentmap_mapsdk_maps_model_OverSeaSourceToX on com_tencent_tencentmap_mapsdk_maps_model_OverSeaSource {
  int toValue() {
    switch (this) {
      case com_tencent_tencentmap_mapsdk_maps_model_OverSeaSource.DEFAULT: return com_tencent_tencentmap_mapsdk_maps_model_OverSeaSource.DEFAULT.index + 0;
      case com_tencent_tencentmap_mapsdk_maps_model_OverSeaSource.SPARE: return com_tencent_tencentmap_mapsdk_maps_model_OverSeaSource.SPARE.index + 0;
      default: return 0;
    }
  }
}

extension com_tencent_tencentmap_mapsdk_maps_model_OverSeaSourceFromX on int {
  com_tencent_tencentmap_mapsdk_maps_model_OverSeaSource tocom_tencent_tencentmap_mapsdk_maps_model_OverSeaSource() {
    switch (this) {
      
      default: return com_tencent_tencentmap_mapsdk_maps_model_OverSeaSource.values[this + 0];
    }
  }
}