// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum com_tencent_lbssearch_object_param_TransitParam_Preference {
  NO_SUBWAY /* null */
}

extension com_tencent_lbssearch_object_param_TransitParam_PreferenceToX on com_tencent_lbssearch_object_param_TransitParam_Preference {
  int toValue() {
    switch (this) {
      case com_tencent_lbssearch_object_param_TransitParam_Preference.NO_SUBWAY: return com_tencent_lbssearch_object_param_TransitParam_Preference.NO_SUBWAY.index + 0;
      default: return 0;
    }
  }
}

extension com_tencent_lbssearch_object_param_TransitParam_PreferenceFromX on int {
  com_tencent_lbssearch_object_param_TransitParam_Preference tocom_tencent_lbssearch_object_param_TransitParam_Preference() {
    switch (this) {
      
      default: return com_tencent_lbssearch_object_param_TransitParam_Preference.values[this + 0];
    }
  }
}