// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum com_tencent_map_lib_MapLanguage {
  LAN_CHINESE /* null */,
  LAN_ENGLISH /* null */
}

extension com_tencent_map_lib_MapLanguageToX on com_tencent_map_lib_MapLanguage {
  int toValue() {
    switch (this) {
      case com_tencent_map_lib_MapLanguage.LAN_CHINESE: return com_tencent_map_lib_MapLanguage.LAN_CHINESE.index + 0;
      case com_tencent_map_lib_MapLanguage.LAN_ENGLISH: return com_tencent_map_lib_MapLanguage.LAN_ENGLISH.index + 0;
      default: return 0;
    }
  }
}

extension com_tencent_map_lib_MapLanguageFromX on int {
  com_tencent_map_lib_MapLanguage tocom_tencent_map_lib_MapLanguage() {
    switch (this) {
      
      default: return com_tencent_map_lib_MapLanguage.values[this + 0];
    }
  }
}