// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:tmap_map_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';

class _com_tencent_lbssearch_httpresponse_UrlConstant_SUB extends java_lang_Object with com_tencent_lbssearch_httpresponse_UrlConstant {}

mixin com_tencent_lbssearch_httpresponse_UrlConstant on java_lang_Object {
  

  static com_tencent_lbssearch_httpresponse_UrlConstant subInstance() => _com_tencent_lbssearch_httpresponse_UrlConstant_SUB();

  @override
  final String tag__ = 'tmap_map_fluttify';

  

  

  
}

extension com_tencent_lbssearch_httpresponse_UrlConstant_Batch on List<com_tencent_lbssearch_httpresponse_UrlConstant> {
  //region methods
  
  //endregion
}