// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////
import 'package:flutter/services.dart';

Future<String> get kQBasicMapViewLayerCenterCoordinateKey async {
  return MethodChannel('me.yohom/tmap_map_fluttify').invokeMethod('getkQBasicMapViewLayerCenterCoordinateKey');
}

Future<String> get kQBasicMapViewLayerZoomLevelKey async {
  return MethodChannel('me.yohom/tmap_map_fluttify').invokeMethod('getkQBasicMapViewLayerZoomLevelKey');
}

Future<String> get kQBasicMapViewLayerRotationKey async {
  return MethodChannel('me.yohom/tmap_map_fluttify').invokeMethod('getkQBasicMapViewLayerRotationKey');
}

Future<String> get kQBasicMapViewLayerOverlookingKey async {
  return MethodChannel('me.yohom/tmap_map_fluttify').invokeMethod('getkQBasicMapViewLayerOverlookingKey');
}
