// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:tmap_map_fluttify/src/ios/ios.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';

class QIndoorPoiInfo extends QPoiInfo  {
  //region constants
  static const String name__ = 'QIndoorPoiInfo';

  @override
  final String tag__ = 'tmap_map_fluttify';

  
  //endregion

  //region creators
  static Future<QIndoorPoiInfo> create__({ bool init = true /* ios only */ }) async {
    final refId = await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod('ObjectFactory::createQIndoorPoiInfo', {'init': init});
    final object = QIndoorPoiInfo()..refId = refId;
    return object;
  }
  
  static Future<List<QIndoorPoiInfo>> create_batch__(int length, { bool init = true /* ios only */ }) async {
    if (false) {
      return Future.error('all args must have same length!');
    }
    final List resultBatch = await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod('ObjectFactory::create_batchQIndoorPoiInfo', {'length': length, 'init': init});
  
    final List<QIndoorPoiInfo> typedResult = resultBatch.map((result) => QIndoorPoiInfo()..refId = result).toList();
    return typedResult;
  }
  
  //endregion

  //region getters
  Future<String> get_levelName() async {
    final __result__ = await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod("QIndoorPoiInfo::get_levelName", {'__this__': this});
    return __result__ == null ? null : (__result__);
  }
  
  Future<String> get_buildingGUID() async {
    final __result__ = await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod("QIndoorPoiInfo::get_buildingGUID", {'__this__': this});
    return __result__ == null ? null : (__result__);
  }
  
  Future<String> get_buildingName() async {
    final __result__ = await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod("QIndoorPoiInfo::get_buildingName", {'__this__': this});
    return __result__ == null ? null : (__result__);
  }
  
  //endregion

  //region setters
  Future<void> set_levelName(String levelName) async {
    await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod('QIndoorPoiInfo::set_levelName', <String, dynamic>{'__this__': this, "levelName": levelName});
  
  
  }
  
  Future<void> set_buildingGUID(String buildingGUID) async {
    await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod('QIndoorPoiInfo::set_buildingGUID', <String, dynamic>{'__this__': this, "buildingGUID": buildingGUID});
  
  
  }
  
  Future<void> set_buildingName(String buildingName) async {
    await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod('QIndoorPoiInfo::set_buildingName', <String, dynamic>{'__this__': this, "buildingName": buildingName});
  
  
  }
  
  //endregion

  //region methods
  
  //endregion

  @override
  String toString() {
    return 'QIndoorPoiInfo{refId: $refId, runtimeType: $runtimeType, tag__: $tag__}';
  }
}

extension QIndoorPoiInfo_Batch on List<QIndoorPoiInfo> {
  //region getters
  Future<List<String>> get_levelName_batch() async {
    final resultBatch = await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod("QIndoorPoiInfo::get_levelName_batch", [for (final __item__ in this) {'__this__': __item__}]);
  
    final typedResult = (resultBatch as List).cast<String>().map((__result__) => __result__).toList();
    return typedResult;
  }
  
  Future<List<String>> get_buildingGUID_batch() async {
    final resultBatch = await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod("QIndoorPoiInfo::get_buildingGUID_batch", [for (final __item__ in this) {'__this__': __item__}]);
  
    final typedResult = (resultBatch as List).cast<String>().map((__result__) => __result__).toList();
    return typedResult;
  }
  
  Future<List<String>> get_buildingName_batch() async {
    final resultBatch = await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod("QIndoorPoiInfo::get_buildingName_batch", [for (final __item__ in this) {'__this__': __item__}]);
  
    final typedResult = (resultBatch as List).cast<String>().map((__result__) => __result__).toList();
    return typedResult;
  }
  
  //endregion

  //region setters
  Future<void> set_levelName_batch(List<String> levelName) async {
    await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('QIndoorPoiInfo::set_levelName_batch', [for (int __i__ = 0; __i__ < length; __i__++) {'__this__': this[__i__], "levelName": levelName[__i__]}]);
  
  
  }
  
  Future<void> set_buildingGUID_batch(List<String> buildingGUID) async {
    await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('QIndoorPoiInfo::set_buildingGUID_batch', [for (int __i__ = 0; __i__ < length; __i__++) {'__this__': this[__i__], "buildingGUID": buildingGUID[__i__]}]);
  
  
  }
  
  Future<void> set_buildingName_batch(List<String> buildingName) async {
    await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('QIndoorPoiInfo::set_buildingName_batch', [for (int __i__ = 0; __i__ < length; __i__++) {'__this__': this[__i__], "buildingName": buildingName[__i__]}]);
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}