// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum QMSDrivingRoutePolicyType {
  QMSDrivingRoutePolicyTypeLeastTime /* 0 */,
  QMSDrivingRoutePolicyTypeLeastFee /* 1 */,
  QMSDrivingRoutePolicyTypeLeastDistance /* 2 */,
  QMSDrivingRoutePolicyTypeRealTraffic /* 3 */
}

extension QMSDrivingRoutePolicyTypeToX on QMSDrivingRoutePolicyType {
  int toValue() {
    switch (this) {
      case QMSDrivingRoutePolicyType.QMSDrivingRoutePolicyTypeLeastTime: return 0;
      case QMSDrivingRoutePolicyType.QMSDrivingRoutePolicyTypeLeastFee: return 1;
      case QMSDrivingRoutePolicyType.QMSDrivingRoutePolicyTypeLeastDistance: return 2;
      case QMSDrivingRoutePolicyType.QMSDrivingRoutePolicyTypeRealTraffic: return 3;
      default: return 0;
    }
  }
}

extension QMSDrivingRoutePolicyTypeFromX on int {
  QMSDrivingRoutePolicyType toQMSDrivingRoutePolicyType() {
    switch (this) {
      case 0: return QMSDrivingRoutePolicyType.QMSDrivingRoutePolicyTypeLeastTime;
      case 1: return QMSDrivingRoutePolicyType.QMSDrivingRoutePolicyTypeLeastFee;
      case 2: return QMSDrivingRoutePolicyType.QMSDrivingRoutePolicyTypeLeastDistance;
      case 3: return QMSDrivingRoutePolicyType.QMSDrivingRoutePolicyTypeRealTraffic;
      default: return QMSDrivingRoutePolicyType.values[this + 0];
    }
  }
}