// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:tmap_map_fluttify/src/ios/ios.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';

class QPolygonView extends QOverlayPathView  {
  //region constants
  static const String name__ = 'QPolygonView';

  @override
  final String tag__ = 'tmap_map_fluttify';

  
  //endregion

  //region creators
  static Future<QPolygonView> create__({ bool init = true /* ios only */ }) async {
    final refId = await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod('ObjectFactory::createQPolygonView', {'init': init});
    final object = QPolygonView()..refId = refId;
    return object;
  }
  
  static Future<List<QPolygonView>> create_batch__(int length, { bool init = true /* ios only */ }) async {
    if (false) {
      return Future.error('all args must have same length!');
    }
    final List resultBatch = await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod('ObjectFactory::create_batchQPolygonView', {'length': length, 'init': init});
  
    final List<QPolygonView> typedResult = resultBatch.map((result) => QPolygonView()..refId = result).toList();
    return typedResult;
  }
  
  //endregion

  //region getters
  Future<QPolygon> get_polygon() async {
    final __result__ = await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod("QPolygonView::get_polygon", {'__this__': this});
    return __result__ == null ? null : (QPolygon()..refId = __result__);
  }
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  Future<QPolygonView> initWithPolygon(QPolygon polygon) async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: QPolygonView@$refId::initWithPolygon([])');
    }
  
    // invoke native method
    final __result__ = await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod('QPolygonView::initWithPolygon', {"polygon": polygon, "__this__": this});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (__result__ == null) {
      return null;
    } else {
      final __return__ = QPolygonView()..refId = __result__;
      return __return__;
    }
  }
  
  //endregion

  @override
  String toString() {
    return 'QPolygonView{refId: $refId, runtimeType: $runtimeType, tag__: $tag__}';
  }
}

extension QPolygonView_Batch on List<QPolygonView> {
  //region getters
  Future<List<QPolygon>> get_polygon_batch() async {
    final resultBatch = await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod("QPolygonView::get_polygon_batch", [for (final __item__ in this) {'__this__': __item__}]);
  
    final typedResult = (resultBatch as List).cast<String>().map((__result__) => QPolygon()..refId = __result__).toList();
    return typedResult;
  }
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  Future<List<QPolygonView>> initWithPolygon_batch(List<QPolygon> polygon) async {
    if (false) {
      return Future.error('all args must have same length!');
    }
  
    // invoke native method
    final resultBatch = await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod('QPolygonView::initWithPolygon_batch', [for (int __i__ = 0; __i__ < length; __i__++) {"polygon": polygon[__i__], "__this__": this[__i__]}]);
  
  
    // convert native result to dart side object
    if (resultBatch == null) {
      return null;
    } else {
      final typedResult = (resultBatch as List).cast<String>().map((__result__) => QPolygonView()..refId = __result__).toList();
      return typedResult;
    }
  }
  
  //endregion
}