// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum QTextureLineDrawType {
  QTextureLineDrawType_ColorLine /* -1 */,
  QTextureLineDrawType_SliceAsBackground /* null */,
  QTextureLineDrawType_RepeatDraw /* null */,
  QTextureLineDrawType_FootPrint /* null */
}

extension QTextureLineDrawTypeToX on QTextureLineDrawType {
  int toValue() {
    switch (this) {
      case QTextureLineDrawType.QTextureLineDrawType_ColorLine: return -1;
      case QTextureLineDrawType.QTextureLineDrawType_SliceAsBackground: return QTextureLineDrawType.QTextureLineDrawType_SliceAsBackground.index + -1;
      case QTextureLineDrawType.QTextureLineDrawType_RepeatDraw: return QTextureLineDrawType.QTextureLineDrawType_RepeatDraw.index + -1;
      case QTextureLineDrawType.QTextureLineDrawType_FootPrint: return QTextureLineDrawType.QTextureLineDrawType_FootPrint.index + -1;
      default: return 0;
    }
  }
}

extension QTextureLineDrawTypeFromX on int {
  QTextureLineDrawType toQTextureLineDrawType() {
    switch (this) {
      case -1: return QTextureLineDrawType.QTextureLineDrawType_ColorLine;
      default: return QTextureLineDrawType.values[this + -1];
    }
  }
}