// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:tmap_map_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';

class _com_tencent_tencentmap_mapsdk_maps_LocationSource_OnLocationChangedListener_SUB extends java_lang_Object with com_tencent_tencentmap_mapsdk_maps_LocationSource_OnLocationChangedListener {}

mixin com_tencent_tencentmap_mapsdk_maps_LocationSource_OnLocationChangedListener on java_lang_Object {
  

  static com_tencent_tencentmap_mapsdk_maps_LocationSource_OnLocationChangedListener subInstance() => _com_tencent_tencentmap_mapsdk_maps_LocationSource_OnLocationChangedListener_SUB();

  @override
  final String tag__ = 'tmap_map_fluttify';

  

  

  
  Future<void> onLocationChanged(android_location_Location var1) async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: com.tencent.tencentmap.mapsdk.maps.LocationSource.OnLocationChangedListener@$refId::onLocationChanged([])');
    }
  
    // invoke native method
    final __result__ = await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod('com.tencent.tencentmap.mapsdk.maps.LocationSource.OnLocationChangedListener::onLocationChanged', {"var1": var1, "__this__": this});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (__result__ == null) {
      return null;
    } else {
      final __return__ = __result__;
      return __return__;
    }
  }
  
}

extension com_tencent_tencentmap_mapsdk_maps_LocationSource_OnLocationChangedListener_Batch on List<com_tencent_tencentmap_mapsdk_maps_LocationSource_OnLocationChangedListener> {
  //region methods
  
  Future<List<void>> onLocationChanged_batch(List<android_location_Location> var1) async {
    if (false) {
      return Future.error('all args must have same length!');
    }
  
    // invoke native method
    final resultBatch = await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod('com.tencent.tencentmap.mapsdk.maps.LocationSource.OnLocationChangedListener::onLocationChanged_batch', [for (int __i__ = 0; __i__ < length; __i__++) {"var1": var1[__i__], "__this__": this[__i__]}]);
  
  
    // convert native result to dart side object
    if (resultBatch == null) {
      return null;
    } else {
      final typedResult = (resultBatch as List).cast<String>().map((__result__) => __result__).toList();
      return typedResult;
    }
  }
  
  //endregion
}