// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:tmap_map_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';

class com_tencent_tencentmap_mapsdk_maps_MapParamConstants extends java_lang_Object  {
  //region constants
  static const String name__ = 'com.tencent.tencentmap.mapsdk.maps.MapParamConstants';

  @override
  final String tag__ = 'tmap_map_fluttify';

  static final int TILE_BMP_SIZE = 256;
  static final int EQUATOR_METERS = 40076000;
  static final int MAP_MODE_NON = -1;
  static final int MAP_MODE_NORMAL = 0;
  static final int MAP_MODE_DARK = 8;
  static final int MAP_MODE_TRAFFIC_NAVI = 9;
  static final int MAP_MODE_TRAFFIC_DARK = 10;
  static final int MAP_MODE_SAT = 11;
  static final int MAP_MODE_NAV = 12;
  static final int MAP_MODE_NAVIGATION_DARK = 13;
  static final int MAP_MODE_EAGLE_DAY = 14;
  static final int MAP_MODE_EAGLE_NIGHT = 15;
  static final int MAP_MODE_SUBWAY = 0;
  static final int MAP_MODE_JAMGRAY = 0;
  static final int MAP_MODE_TRAFFIC = 5;
  static final int MAP_MODE_NAVIGATION_JAMGRAY = 0;
  static final int MAP_MODE_NAVIGATION_TRAFFIC = 7;
  static final int MAP_MODE_NAVIGATION_SMALL = 9;
  static final int MASK_LAYER_NONE = -1;
  static final int MASK_LAYER_UNDER_MARKER = 0;
  static final int MASK_LAYER_UNDER_LINE = 1;
  static final int STYLE_OFFSET = 1000;
  //endregion

  //region creators
  static Future<com_tencent_tencentmap_mapsdk_maps_MapParamConstants> create__() async {
    final refId = await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod('ObjectFactory::createcom_tencent_tencentmap_mapsdk_maps_MapParamConstants__', );
    final object = com_tencent_tencentmap_mapsdk_maps_MapParamConstants()..refId = refId;
    return object;
  }
  
  static Future<List<com_tencent_tencentmap_mapsdk_maps_MapParamConstants>> create_batch__(int length) async {
    if (false) {
      return Future.error('all args must have same length!');
    }
    final List resultBatch = await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod('ObjectFactory::create_batchcom_tencent_tencentmap_mapsdk_maps_MapParamConstants__', {'length': length});
  
    final List<com_tencent_tencentmap_mapsdk_maps_MapParamConstants> typedResult = resultBatch.map((result) => com_tencent_tencentmap_mapsdk_maps_MapParamConstants()..refId = result).toList();
    return typedResult;
  }
  
  //endregion

  //region getters
  static Future<double> get_static_MAX_SKEW_ANGLE() async {
    final __result__ = await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod("com.tencent.tencentmap.mapsdk.maps.MapParamConstants::get_MAX_SKEW_ANGLE", );
    return __result__ == null ? null : (__result__);
  }
  
  static Future<double> get_static_MIN_SKEW_ANGLE() async {
    final __result__ = await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod("com.tencent.tencentmap.mapsdk.maps.MapParamConstants::get_MIN_SKEW_ANGLE", );
    return __result__ == null ? null : (__result__);
  }
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  //endregion

  @override
  String toString() {
    return 'com_tencent_tencentmap_mapsdk_maps_MapParamConstants{refId: $refId, runtimeType: $runtimeType, tag__: $tag__}';
  }
}

extension com_tencent_tencentmap_mapsdk_maps_MapParamConstants_Batch on List<com_tencent_tencentmap_mapsdk_maps_MapParamConstants> {
  //region getters
  Future<List<double>> get_static_MAX_SKEW_ANGLE_batch() async {
    final resultBatch = await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod("com.tencent.tencentmap.mapsdk.maps.MapParamConstants::get_MAX_SKEW_ANGLE_batch", [for (final __item__ in this) {'__this__': __item__}]);
  
    final typedResult = (resultBatch as List).cast<double>().map((__result__) => __result__).toList();
    return typedResult;
  }
  
  Future<List<double>> get_static_MIN_SKEW_ANGLE_batch() async {
    final resultBatch = await MethodChannel('me.yohom/tmap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('tmap_map_fluttify'))).invokeMethod("com.tencent.tencentmap.mapsdk.maps.MapParamConstants::get_MIN_SKEW_ANGLE_batch", [for (final __item__ in this) {'__this__': __item__}]);
  
    final typedResult = (resultBatch as List).cast<double>().map((__result__) => __result__).toList();
    return typedResult;
  }
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  //endregion
}