// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum com_tencent_map_tools_json_FieldNameStyle {
  HUMP /* null */,
  UNDERLINE /* null */
}

extension com_tencent_map_tools_json_FieldNameStyleToX on com_tencent_map_tools_json_FieldNameStyle {
  int toValue() {
    switch (this) {
      case com_tencent_map_tools_json_FieldNameStyle.HUMP: return com_tencent_map_tools_json_FieldNameStyle.HUMP.index + 0;
      case com_tencent_map_tools_json_FieldNameStyle.UNDERLINE: return com_tencent_map_tools_json_FieldNameStyle.UNDERLINE.index + 0;
      default: return 0;
    }
  }
}

extension com_tencent_map_tools_json_FieldNameStyleFromX on int {
  com_tencent_map_tools_json_FieldNameStyle tocom_tencent_map_tools_json_FieldNameStyle() {
    switch (this) {
      
      default: return com_tencent_map_tools_json_FieldNameStyle.values[this + 0];
    }
  }
}